# Generated by Django 4.2.11 on 2024-04-15 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_channels', '0002_paidcontent'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paidcontent',
            table='paid_content',
        ),
    ]
