

CREATE TABLE IF NOT EXISTS `users` (
    `telegram_id` BIGINT NOT NULL,
    `username` VARCHAR(255) NULL,
    `full_name` VARCHAR(255) NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`telegram_id`)
    ) ENGINE = INNODB DEFAULT CHARSET = utf8mb4;
    
CREATE TABLE IF NOT EXISTS `orders` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT NOT NULL,
    `order_info` JSON NOT NULL,
    `amount` DECIMAL(16, 4) NOT NULL,
    `paid` BOOLEAN NOT NULL DEFAULT FALSE,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`user_id`) REFERENCES `users` (`telegram_id`) ON DELETE CASCADE
    ) ENGINE = INNODB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS `transactions` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT NOT NULL,
    `pay_address` VARCHAR(255) NOT NULL,
    `currency` VARCHAR(16) NOT NULL,
    `usd_amount` DECIMAL(16, 4) NOT NULL,
    `pay_amount` DECIMAL(16, 8) NOT NULL,
    `paid` BOOLEAN NOT NULL DEFAULT FALSE,
    `payment_id` INT NULL,
    `order_id` INT NULL,
    `comment` VARCHAR(255) NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`user_id`) REFERENCES `users` (`telegram_id`) ON DELETE CASCADE,
    FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`)
    ) ENGINE = INNODB DEFAULT CHARSET = utf8mb4;
